<?php

namespace App\Repository\Category;

/**
 * Label
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Label extends \Doctrine\ORM\EntityRepository {

}
