parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

#        dql:
#            string_functions:
#                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
#                IFNULL: DoctrineExtensions\Query\Mysql\IfNull
#                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat


        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Closas\ShopBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Closas/ShopBundle/Entity'
                prefix: 'Closas\ShopBundle\Entity'
                alias: ClosasShopBundle
            Closas\AdminBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Closas/AdminBundle/Entity'
                prefix: 'Closas\AdminBundle\Entity'
                alias: ClosasAdminBundle
            Closas\UserBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Closas/UserBundle/Entity'
                prefix: 'Closas\UserBundle\Entity'
                alias: ClosasUserBundle
            DoctrineExtensions\Query:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DoctrineExtensions/Query/Mysql'
                prefix: 'DoctrineExtensions\Query\Mysql'
                alias: DoctrineExtensions



