<?php

namespace Closas\ShopBundle\Entity\Repository\Mail;

/**
 * Send
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Send extends \Doctrine\ORM\EntityRepository {

}
