<?php

namespace App\Entity\Repository\Nivoslider;

/**
 * Description
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Item extends \Doctrine\ORM\EntityRepository {

    public function findAllByArray($lang_short_name, $arr_items_ids) {

        $em = $this->getEntityManager();
        $lang = $em->getRepository('ClosasShopBundle:Language')->findOneBy(array('short_name' => $lang_short_name));
        $em = $this->getEntityManager();
        $result = $em->getRepository('ClosasShopBundle:Nivoslider\Item')
                ->createQueryBuilder('i')
                ->select('i')
                ->where('i.lang=:langId')
                ->andWhere('i.nivoslider IN (:itemIds)')
                ->setParameter('langId', $lang->getId())
                ->setParameter('itemIds', $arr_items_ids)
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        return $result;
    }

}
