<?php

namespace App\Entity\Repository\Calendar;

/**
 * Calendar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Typ extends \Doctrine\ORM\EntityRepository {

}
