imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ClosasShopBundle/Resources/config/services.yml" }
    - { resource: "@ClosasAdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    upload_directory: '%kernel.root_dir%/../web/media/dynamisch'
    products_directory: '%kernel.root_dir%/../web/media/import/csv'
    container.autowiring.strict_mode: true
framework:
    #esi:             ~
    translator:
        fallbacks: "%locale%"
        paths: ['%kernel.root_dir%/../translations']
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 3600
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        common: "@helper.common"
        order: "@helper.order"
        navigation: "@helper.navigation"
        calendar: "@helper.calendar"
    form_themes:
            - 'bootstrap_3_kidlou_horizontal_layout.html.twig'
    #exception_controller:  ClosasShopBundle:Exception:showException

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat


# Swiftmailer Configuration
swiftmailer:
    default_mailer: mailer
    mailers:
        mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            #port:      "%mailer_port"
            #encryption: %mailer_encryption%
            #auth_mode:  "%mailer_auth_mode%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            #spool:     { type: memory }
        mailercommon:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            #port:      "%mailer_port"
            #encryption: %mailer_encryption%
            #auth_mode:  "%mailer_auth_mode%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
