imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ClosasShopBundle/Resources/config/services.yml" }
    - { resource: "@ClosasAdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    upload_directory: '%kernel.root_dir%/../web/media/dynamisch'
    products_directory: '%kernel.root_dir%/../web/media/import/csv'
    container.autowiring.strict_mode: true


