closas_admin:
    resource: "@ClosasAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

closas_user:
    resource: "@ClosasUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/user/
    requirements:
        _locale: fr|de|en|es

closas_shop:
    resource: "@ClosasShopBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: fr|de|en|es


#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    prefix:   /

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fr/
        prefix:   /{_locale}/
        permanent: true
#app_category:
#    resource: "."
#    type: category