<?php

namespace Closas\ShopBundle\Entity\Repository\Content;

/**
 * Calendar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group extends \Doctrine\ORM\EntityRepository {

}
