<?php

namespace Closas\ShopBundle\Entity\Repository\Map;

/**
 * OrderProductAdditional
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductAdditional extends \Doctrine\ORM\EntityRepository {

}
