web_profiler:
    toolbar: true
    intercept_redirects: false
    # excluded_ajax_paths:  ^/(app(_[\\w]+)?\\.php/)?_wdt
    excluded_ajax_paths:  ^/*
framework:
    profiler: { only_exceptions: false }
