<?php

namespace App\Repository;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUser extends \Doctrine\ORM\EntityRepository {

}
