<?php

namespace App\Repository;

/**
 * Content
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Content extends \Doctrine\ORM\EntityRepository {

    /**
     *
     * @param type $category
     * @param type $lang
     * @return type $content
     */
    public function findByCategory($category, $lang) {
        return $this->createQueryBuilder('co')
                        ->innerJoin('co.categories', 'ca')
                        ->where('ca.id = (:category) AND co.status = 1 AND co.lang = (:lang)')
                        ->setParameter('category', $category->getId())
                        ->setParameter('lang', $lang)
                        ->orderBy('co.created_at', 'DESC')
                        ->getQuery()
                        ->getResult();
    }

    /**
     *
     * @param type $arr_categories
     * @param type $lang
     * @return type $contents
     */
    public function findByCategories($arr_categories, $lang) {
        return $this->createQueryBuilder('co')
                        ->innerJoin('co.categories', 'ca')
                        ->where('ca.id IN (:arrcategories) AND co.status = 1 AND co.lang = (:lang)')
                        ->setParameter('arrcategories', $arr_categories)
                        ->setParameter('lang', $lang)
                        ->getQuery()
                        ->getResult();
    }

    /**
     *
     * @param type $url_key
     * @param string $lang
     * @return type
     */
    public function findByGroupUrlKey($url_key, $lang) {
        return $this->createQueryBuilder('co')
                        ->innerJoin('co.group', 'gr')
                        ->where('gr.url_key = (:url_key) AND co.lang = (:lang)')
                        ->setParameter('url_key', $url_key)
                        ->setParameter('lang', $lang)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

}
