<?php

namespace App\Repository;

/**
 * Deliver
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Deliver extends \Doctrine\ORM\EntityRepository {

    public function findByMonthYear($currentmonth, $currentyear, $aftermonth, $afteryear) {

        $fromTime = new \DateTime($currentyear . '-' . $currentmonth . '-01');
        $toTime = new \DateTime($afteryear . '-' . $aftermonth . '-01');
        $qb = $this->createQueryBuilder('p')
                ->where('p.date >= :fromTime')
                ->andWhere('p.date < :toTime')
                ->setParameter('fromTime', $fromTime)
                ->setParameter('toTime', $toTime);
        return $qb->getQuery()->getResult();
    }

}
