<?php

namespace App\Repository;

/**
 * Gift
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Gift extends \Doctrine\ORM\EntityRepository {

}
