<?php

namespace App\Repository;

/**
 * Inbox
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inbox extends \Doctrine\ORM\EntityRepository {

}
