<?php

namespace App\Repository;

/**
 * Language
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Language extends \Doctrine\ORM\EntityRepository {

}
