<?php

namespace Closas\ShopBundle\Entity\Repository\Product;

/**
 * Description
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Description extends \Doctrine\ORM\EntityRepository {
    
}
