<?php

namespace App\Repository\Quote;

/**
 * Calendar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Address extends \Doctrine\ORM\EntityRepository {

}
