services:
    helper.imageresizer: '@App\Service\ImageResizer'
    helper.navigation: '@App\Service\Navigation'
    helper.common: '@App\Service\Common'
    helper.product: '@App\Service\Product'
    helper.content: '@App\Service\Content'
    helper.cart: '@App\Service\Cart'
    helper.calendar: '@App\Service\Calendar'
    helper.image: '@App\Service\Image'
    helper.quote: '@App\Service\Quote'
    helper.order: '@App\Service\Order'
    helper.payment: '@App\Service\Payment'
    service.language: '@App\Service\Parameter'
    #closas.locale.listener: '@App\Listener\LocalListener'
    authentication_handler: '@App\Handler\AuthenticationHandler'

