services:
    helper.imageresizer: '@Closas\ShopBundle\Helper\ImageResizer'
    helper.navigation: '@Closas\ShopBundle\Helper\Navigation'
    helper.common: '@Closas\ShopBundle\Helper\Common'
    helper.product: '@Closas\ShopBundle\Helper\Product'
    helper.content: '@Closas\ShopBundle\Helper\Content'
    helper.cart: '@Closas\ShopBundle\Helper\Cart'
    helper.calendar: '@Closas\ShopBundle\Helper\Calendar'
    helper.image: '@Closas\ShopBundle\Helper\Image'
    helper.order: '@Closas\ShopBundle\Helper\Order'
    helper.payment: '@Closas\ShopBundle\Helper\Payment'
    closas.locale.listener: '@Closas\AdminBundle\Listener\LocalListener'
    authentication_handler: '@Closas\UserBundle\Handler\AuthenticationHandler'

