closas_admin:
    resource: ../../src/Controller/Admin/
    type:     annotation
    prefix:   /admin/

closas_user:
    resource: ../../src/Controller/User/
    type:     annotation
    prefix:   /{_locale}/user/
    requirements:
        _locale: fr|de|en|es

closas_shop:
    resource: ../../src/Controller/Shop/
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: fr|de|en|es
