#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#closas_admin:
#    resource: ../../src/Closas/AdminBundle/Controller/
#    type:     annotation
#    prefix:   /admin/

#closas_user:
#    resource: ../../src/Closas/UserBundle/Controller/
#    type:     annotation
#    prefix:   /{_locale}/user/
#    requirements:
#        _locale: fr|de|en|es

closas_shop:
    resource: ../../src/Controller/Shop/
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: fr|de|en|es

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    prefix:   /

# redirecting the root
#homepage:
#    path: /fr/
#    requirements:
#            _locale: fr|de|en|es
#    defaults:
#        _controller: App\Controller\Shop\StartController::indexAction
        #path: /fr/
#        prefix:   /{_locale}/
#        permanent: true


