# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
    - { resource: legacy_aliases.yaml }

parameters:
    locale: fr
    upload_directory: '%kernel.root_dir%/../web/media/dynamisch'
    products_directory: '%kernel.root_dir%/../web/media/import/csv'
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # this makes public all the services defined in this file
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']


    Psr\Log\LoggerInterface: "@logger"


    App\Service\ImageResizer:

    App\Service\Navigation:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container"]

    App\Service\Common:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@translator.default","@service_container","@helper.navigation"]

    App\Service\Product:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Content:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Cart:
        arguments: ["@doctrine.orm.entity_manager","@helper.common"]

    App\Service\Calendar:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container"]

    App\Service\Image:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@kernel","@helper.imageresizer"]

    App\Service\Payment:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Order:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container", "@helper.common", "@mailer"]


    App\Listener\LocalListener:
        class: App\Listener\LocaleListener
        arguments: ["@translator"]
        tags:
          - { name: kernel.event_subscriber }

    App\Handler\AuthenticationHandler:
        arguments: ["@service_container","@router"]
