# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
    - { resource: legacy_aliases.yaml }

parameters:
    locale: fr
    upload_directory: '%kernel.root_dir%/../web/media/dynamisch'
    products_directory: '%kernel.root_dir%/../web/media/import/csv'
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # this makes public all the services defined in this file
# default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Tests}'



#    AppBundle\:
#        resource: '../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
#        exclude: '../src/AppBundle/{Entity,Tests}'

#    Closas\ShopBundle\:
#        resource: '../src/Closas/ShopBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
#        exclude: '../src/Closas/ShopBundle/{Entity,Tests}'

#    Closas\UserBundle\:
#        resource: '../src/Closas/UserBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
#        exclude: '../src/Closas/UserBundle/{Entity,Tests}'

#    Closas\AdminBundle\:
#        resource: '../src/Closas/AdminBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
#        exclude: '../src/Closas/AdminBundle/{Entity,Tests,AdminBundle}'


    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services


    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']


#    AppBundle\Controller\:
#        resource: '../src/AppBundle/Controller'
#        public: true
#        tags: ['controller.service_arguments']

#    Closas\ShopBundle\Controller\:
#        resource: '../src/Closas/ShopBundle/Controller'
#        public: true
#        tags: ['controller.service_arguments']

#    Closas\UserBundle\Controller\:
#        resource: '../src/Closas/UserBundle/Controller'
#        public: true
#        tags: ['controller.service_arguments']

#    Closas\AdminBundle\Controller\:
#        resource: '../src/Closas/AdminBundle/Controller'
#        public: true
#        tags: ['controller.service_arguments']

#    Closas\AdminBundle\Listener\:
#        resource: '../src/Closas/AdminBundle/Listener    '
#        public: true
#        tags: ['controller.service_arguments']

    Psr\Log\LoggerInterface: "@logger"



    Closas\ShopBundle\Helper\ImageResizer:
#    helper.imageresizer:
#        class: Closas\ShopBundle\Helper\ImageResizer

    App\Service\Navigation:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container"]

    App\Service\Common:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@translator.default","@service_container","@helper.navigation"]

    App\Service\Product:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Content:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Cart:
        arguments: ["@doctrine.orm.entity_manager","@helper.common"]

    App\Service\Calendar:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container"]

    App\Service\Image:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@kernel","@helper.imageresizer"]

    App\Service\Payment:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@helper.common"]

    App\Service\Order:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","@service_container", "@helper.common", "@mailer"]


    App\Listener\LocalListener:
        class: App\Listener\LocaleListener
        arguments: ["@translator"]
        tags:
          - { name: kernel.event_subscriber }

    App\Handler\AuthenticationHandler:
        arguments: ["@service_container","@router"]

#    app.routing_loader:
#        class: Closas\ShopBundle\Routing\CategoryLoader
#        tags:
#            - { name: routing.loader }