<?php

namespace App\Entity\Repository\Map;

/**
 * CategoryProduct
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryProduct extends \Doctrine\ORM\EntityRepository {

}
