<?php

namespace App\Entity\Repository\Map;

/**
 * QuoteProductAdditional
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProductAdditional extends \Doctrine\ORM\EntityRepository {

}
