<?php

namespace App\Repository\Map;

/**
 * CategoryLink
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLink extends \Doctrine\ORM\EntityRepository
{
}
