<?php

namespace App\Repository\Map;

/**
 * QuoteProductAdditional
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProductAdditional extends \Doctrine\ORM\EntityRepository {

    /**
     *
     * @param type $url_key
     * @param type $lang
     * @return type products
     */
    public function getChildrens($quote_id, $product_id) {

        return $this->createQueryBuilder('qpa')
                        ->where('qpa.quote = :quote_id AND qpa.parent = :product_id')
                        ->setParameter('quote_id', $quote_id)
                        ->setParameter('product_id', $product_id)
                        ->getQuery()
                        ->getResult();
    }

}
