<?php

namespace Closas\ShopBundle\Entity\Repository\Order;

/**
 * Item
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Item extends \Doctrine\ORM\EntityRepository {

}
