<?php

namespace Closas\ShopBundle\Entity\Repository;

/**
 * Calendar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Nivoslider extends \Doctrine\ORM\EntityRepository {

}
