<?php

namespace Closas\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Postalcode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Postalcode extends \Doctrine\ORM\EntityRepository {

    public function findAllPlzName($plzname) {
        return $this->createQueryBuilder('p')
                        ->where("p.plz LIKE :plzname OR p.name LIKE :plzname")
                        ->setParameter('plzname', $plzname . '%')
                        ->getQuery()
                        ->getResult();
    }

}
