<?php

namespace Closas\ShopBundle\Entity\Repository;

//use DoctrineExtensions\Query\Mysql\DateFormat;

/**
 * Quote
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Zone extends \Doctrine\ORM\EntityRepository {

}
