<?php

namespace App\Entity\Repository;

/**
 * Price
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Price extends \Doctrine\ORM\EntityRepository
{
}
