<?php

namespace App\Repository\Order;

/**
 * Payment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Payment extends \Doctrine\ORM\EntityRepository {

}
