<?php

namespace Closas\ShopBundle\Entity\Repository\Gift;

/**
 * Coupon
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Coupon extends \Doctrine\ORM\EntityRepository {

}
