<?php

namespace App\Repository\Gift;

/**
 * Text
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Text extends \Doctrine\ORM\EntityRepository {

}
